# Generated by Django 2.2.11 on 2020-05-18 12:53

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid
import vng_api_common.fields
import vng_api_common.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Klant",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Unieke resource identifier (UUID4)",
                        unique=True,
                    ),
                ),
                (
                    "voornaam",
                    models.CharField(
                        blank=True,
                        help_text="De voornaam, voorletters of roepnaam van de klant.",
                        max_length=200,
                    ),
                ),
                (
                    "achternaam",
                    models.CharField(
                        blank=True,
                        help_text="De achternaam van de klant.",
                        max_length=200,
                    ),
                ),
                (
                    "adres",
                    models.CharField(
                        blank=True, help_text="Het adres van de klant.", max_length=1000
                    ),
                ),
                (
                    "functie",
                    models.CharField(
                        blank=True, help_text="De functie van de klant.", max_length=200
                    ),
                ),
                (
                    "telefoonnummer",
                    models.CharField(
                        blank=True,
                        help_text="Het mobiele of vaste telefoonnummer van de klant.",
                        max_length=20,
                    ),
                ),
                (
                    "emailadres",
                    models.EmailField(
                        blank=True,
                        help_text="Het e-mail adres van de klant.",
                        max_length=254,
                    ),
                ),
                (
                    "subject",
                    models.URLField(
                        blank=True,
                        help_text="URL-referentie naar een subject",
                        max_length=1000,
                    ),
                ),
                (
                    "subject_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("natuurlijk_persoon", "Natuurlijk persoon"),
                            ("niet_natuurlijk_persoon", "Niet-natuurlijk persoon"),
                            ("vestiging", "Vestiging"),
                        ],
                        help_text="Type van de `subject`.",
                        max_length=100,
                        null=True,
                    ),
                ),
            ],
            options={"verbose_name": "klant", "verbose_name_plural": "klanten",},
            bases=(vng_api_common.models.APIMixin, models.Model),
        ),
        migrations.CreateModel(
            name="NatuurlijkPersoon",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "inp_bsn",
                    vng_api_common.fields.BSNField(
                        blank=True,
                        help_text="Het burgerservicenummer, bedoeld in artikel 1.1 van de Wet algemene bepalingen burgerservicenummer.",
                        max_length=9,
                    ),
                ),
                (
                    "anp_identificatie",
                    models.CharField(
                        blank=True,
                        help_text="Het door de gemeente uitgegeven unieke nummer voor een ANDER NATUURLIJK PERSOON",
                        max_length=17,
                    ),
                ),
                (
                    "inp_a_nummer",
                    models.CharField(
                        blank=True,
                        help_text="Het administratienummer van de persoon, bedoeld in de Wet BRP",
                        max_length=10,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="a-nummer-incorrect-format",
                                message="inpA_nummer must consist of 10 digits",
                                regex="^[1-9][0-9]{9}$",
                            )
                        ],
                    ),
                ),
                (
                    "geslachtsnaam",
                    models.CharField(
                        blank=True,
                        help_text="De stam van de geslachtsnaam.",
                        max_length=200,
                    ),
                ),
                (
                    "voorvoegsel_geslachtsnaam",
                    models.CharField(blank=True, max_length=80),
                ),
                (
                    "voorletters",
                    models.CharField(
                        blank=True,
                        help_text="De verzameling letters die gevormd wordt door de eerste letter van alle in volgorde voorkomende voornamen.",
                        max_length=20,
                    ),
                ),
                (
                    "voornamen",
                    models.CharField(
                        blank=True,
                        help_text="Voornamen bij de naam die de persoon wenst te voeren.",
                        max_length=200,
                    ),
                ),
                (
                    "geslachtsaanduiding",
                    models.CharField(
                        blank=True,
                        choices=[("m", "Man"), ("v", "Vrouw"), ("o", "Onbekend")],
                        help_text="Een aanduiding die aangeeft of de persoon een man of een vrouw is, of dat het geslacht nog onbekend is.",
                        max_length=1,
                    ),
                ),
                ("geboortedatum", models.CharField(blank=True, max_length=18)),
                (
                    "klant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="natuurlijk_persoon",
                        to="datamodel.Klant",
                    ),
                ),
            ],
            options={"verbose_name": "natuurlijk persoon",},
        ),
        migrations.CreateModel(
            name="NietNatuurlijkPersoon",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "inn_nnp_id",
                    vng_api_common.fields.RSINField(
                        blank=True,
                        help_text="Het door een kamer toegekend uniek nummer voor de INGESCHREVEN NIET-NATUURLIJK PERSOON",
                        max_length=9,
                    ),
                ),
                (
                    "ann_identificatie",
                    models.CharField(
                        blank=True,
                        help_text="Het door de gemeente uitgegeven unieke nummer voor een ANDER NIET-NATUURLIJK PERSOON",
                        max_length=17,
                    ),
                ),
                (
                    "statutaire_naam",
                    models.TextField(
                        blank=True,
                        help_text="Naam van de niet-natuurlijke persoon zoals deze is vastgelegd in de statuten (rechtspersoon) of in de vennootschapsovereenkomst is overeengekomen (Vennootschap onder firma of Commanditaire vennootschap).",
                        max_length=500,
                    ),
                ),
                (
                    "inn_rechtsvorm",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("besloten_vennootschap", "Besloten Vennootschap"),
                            (
                                "cooperatie_europees_economische_samenwerking",
                                "Cooperatie, Europees Economische Samenwerking",
                            ),
                            (
                                "europese_cooperatieve_venootschap",
                                "Europese Cooperatieve Venootschap",
                            ),
                            (
                                "europese_naamloze_vennootschap",
                                "Europese Naamloze Vennootschap",
                            ),
                            ("kerkelijke_organisatie", "Kerkelijke Organisatie"),
                            ("naamloze_vennootschap", "Naamloze Vennootschap"),
                            (
                                "onderlinge_waarborg_maatschappij",
                                "Onderlinge Waarborg Maatschappij",
                            ),
                            (
                                "overig_privaatrechtelijke_rechtspersoon",
                                "Overig privaatrechtelijke rechtspersoon",
                            ),
                            ("stichting", "Stichting"),
                            ("vereniging", "Vereniging"),
                            ("vereniging_van_eigenaars", "Vereniging van Eigenaars"),
                            (
                                "publiekrechtelijke_rechtspersoon",
                                "Publiekrechtelijke Rechtspersoon",
                            ),
                            ("vennootschap_onder_firma", "Vennootschap onder Firma"),
                            ("maatschap", "Maatschap"),
                            ("rederij", "Rederij"),
                            (
                                "commanditaire_vennootschap",
                                "Commanditaire vennootschap",
                            ),
                            (
                                "kapitaalvennootschap_binnen_eer",
                                "Kapitaalvennootschap binnen EER",
                            ),
                            (
                                "overige_buitenlandse_rechtspersoon_vennootschap",
                                "Overige buitenlandse rechtspersoon vennootschap",
                            ),
                            (
                                "kapitaalvennootschap_buiten_eer",
                                "Kapitaalvennootschap buiten EER",
                            ),
                        ],
                        help_text="De juridische vorm van de NIET-NATUURLIJK PERSOON.",
                        max_length=50,
                    ),
                ),
                (
                    "bezoekadres",
                    models.CharField(
                        blank=True,
                        help_text="De gegevens over het adres van de NIET-NATUURLIJK PERSOON",
                        max_length=1000,
                    ),
                ),
                (
                    "klant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="niet_natuurlijk_persoon",
                        to="datamodel.Klant",
                    ),
                ),
            ],
            options={"verbose_name": "niet-natuurlijk persoon",},
        ),
        migrations.CreateModel(
            name="Vestiging",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vestigings_nummer",
                    models.CharField(
                        blank=True,
                        help_text="Een korte unieke aanduiding van de Vestiging.",
                        max_length=24,
                    ),
                ),
                (
                    "handelsnaam",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(blank=True, max_length=625),
                        default=list,
                        help_text="De naam van de vestiging waaronder gehandeld wordt.",
                        size=None,
                    ),
                ),
                (
                    "klant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="datamodel.Klant",
                    ),
                ),
            ],
            options={"verbose_name": "vestiging",},
        ),
        migrations.CreateModel(
            name="SubVerblijfBuitenland",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lnd_landcode",
                    models.CharField(
                        help_text="De code, behorende bij de landnaam, zoals opgenomen in de Land/Gebied-tabel van de BRP.",
                        max_length=4,
                    ),
                ),
                (
                    "lnd_landnaam",
                    models.CharField(
                        help_text="De naam van het land, zoals opgenomen in de Land/Gebied-tabel van de BRP.",
                        max_length=40,
                    ),
                ),
                ("sub_adres_buitenland_1", models.CharField(blank=True, max_length=35)),
                ("sub_adres_buitenland_2", models.CharField(blank=True, max_length=35)),
                ("sub_adres_buitenland_3", models.CharField(blank=True, max_length=35)),
                (
                    "natuurlijkpersoon",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_verblijf_buitenland",
                        to="datamodel.NatuurlijkPersoon",
                    ),
                ),
                (
                    "nietnatuurlijkpersoon",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_verblijf_buitenland",
                        to="datamodel.NietNatuurlijkPersoon",
                    ),
                ),
                (
                    "vestiging",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_verblijf_buitenland",
                        to="datamodel.Vestiging",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Adres",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "aoa_identificatie",
                    models.CharField(
                        help_text="De unieke identificatie van het OBJECT",
                        max_length=100,
                    ),
                ),
                ("wpl_woonplaats_naam", models.CharField(max_length=80)),
                (
                    "gor_openbare_ruimte_naam",
                    models.CharField(
                        help_text="Een door het bevoegde gemeentelijke orgaan aan een OPENBARE RUIMTE toegekende benaming",
                        max_length=80,
                    ),
                ),
                (
                    "aoa_huisnummer",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MaxValueValidator(99999)]
                    ),
                ),
                ("aoa_huisletter", models.CharField(blank=True, max_length=1)),
                (
                    "aoa_huisnummertoevoeging",
                    models.CharField(blank=True, max_length=4),
                ),
                ("aoa_postcode", models.CharField(blank=True, max_length=7)),
                (
                    "inp_locatiebeschrijving",
                    models.CharField(blank=True, max_length=1000),
                ),
                (
                    "natuurlijkpersoon",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verblijfsadres",
                        to="datamodel.NatuurlijkPersoon",
                    ),
                ),
                (
                    "vestiging",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verblijfsadres",
                        to="datamodel.Vestiging",
                    ),
                ),
            ],
        ),
    ]
