# Generated by Django 2.2.11 on 2020-05-27 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("datamodel", "0003_auto_20200527_1052"),
    ]

    operations = [
        migrations.RemoveField(model_name="klant", name="adres",),
        migrations.AlterField(
            model_name="klantadres",
            name="klant",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="adres",
                to="datamodel.Klant",
            ),
        ),
    ]
