# Generated by Django 2.2.11 on 2020-05-28 10:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datamodel", "0004_auto_20200527_1243"),
    ]

    operations = [
        migrations.AlterField(
            model_name="klant",
            name="website_url",
            field=models.URLField(
                help_text="Het label of etiket dat aan de specifieke informatiebron, zoals een webpagina, een bestand of een plaatje op internet is toegewezen waar de KLANT in de regel op het internet vindbaar is.",
                max_length=1000,
                verbose_name="Website URL",
            ),
        ),
        migrations.AlterField(
            model_name="klantadres",
            name="huisnummer",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MaxValueValidator(99999)],
            ),
        ),
        migrations.AlterField(
            model_name="klantadres",
            name="landcode",
            field=models.CharField(
                blank=True,
                help_text="De code, behorende bij de landnaam, zoals opgenomen in de Land/Gebied-tabel van de BRP.",
                max_length=4,
            ),
        ),
        migrations.AlterField(
            model_name="klantadres",
            name="woonplaats_naam",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name="verblijfsadres",
            name="huisnummer",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MaxValueValidator(99999)],
            ),
        ),
        migrations.AlterField(
            model_name="verblijfsadres",
            name="woonplaats_naam",
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
