dist: xenial

language: python

cache: pip

python: 3.7

services:
  - postgresql

addons:
  postgresql: "10"

env:
  global:
  - DJANGO_SETTINGS_MODULE=klanten.conf.ci
  - SECRET_KEY=dummy
  - DB_PASSWORD=
  - DB_USER=postgres
  - DEPLOYMENT=cmc

install:
  - pip install -r requirements/ci.txt
  - pip install codecov
  - npm ci
  - npm run build

jobs:
  include:
    # Run jobs in parallel in stage Tests
    - stage: "Tests"
      name: "Unit tests"
      script:
        - python src/manage.py collectstatic --noinput --link
        - coverage run src/manage.py test src

    - name: "Code imports"
      before_install: skip
      install:
        - pip install isort
      before_script: skip
      script: isort --recursive --check-only --diff .

    - name: "Code format"
      before_install: skip
      install:
        - pip install black
      before_script: skip
      script: black --check src --diff

after_success:
  - codecov
