# Inspired by https://docs.docker.com/compose/django/
version: '3.4'

services:
  db:
    image: postgres:11-alpine
    environment:
      - POSTGRES_USER=${DB_USER:-klanten}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-klanten}
  web:
    build: .
    image: vngr/klanten-api
    environment:
      - DJANGO_SETTINGS_MODULE=klanten.conf.docker
      - SECRET_KEY=${SECRET_KEY}
      - DB_USER=${DB_USER:-klanten}
      - DB_PASSWORD=${DB_PASSWORD:-klanten}
    volumes:
      - ./fixtures:/app/fixtures
    ports:
      - 8006:8000
    depends_on:
      - db
